import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Outfit Engine",
  description: "Terms governing your use of the Outfit Engine service.",
};

const LAST_UPDATED = "April 7, 2026";

const sections = [
  {
    id: "acceptance-of-terms",
    heading: "Acceptance of Terms",
    content: [
      "By creating an account or using Outfit Engine, you agree to these terms. If you do not agree, do not use the service.",
      "Outfit Engine is currently in alpha. The service is provided as-is, without warranty of any kind, and may change significantly or become unavailable at any time. We will try to give reasonable notice of major changes, but this is not guaranteed during the alpha period.",
      "These terms may be updated from time to time. Continued use of the service after updates constitutes acceptance of the revised terms.",
    ],
  },
  {
    id: "use-of-service",
    heading: "Use of Service",
    content: [
      "You must be at least 13 years old to use Outfit Engine. By using the service you represent that you meet this requirement.",
      "You are responsible for the content you upload. Do not upload images that contain nudity, depict identifiable third parties without consent, or violate any applicable law. Outfit Engine is designed for clothing and wardrobe items only.",
      "Your clothing images are analyzed by Claude, an AI model developed by Anthropic. By uploading images you consent to this processing. Images are stored to support the styling features of the service and are not used to train AI models without explicit consent.",
      "You may not use Outfit Engine to scrape data, reverse-engineer the AI systems, or attempt to gain unauthorized access to any part of the platform.",
    ],
  },
  {
    id: "affiliate-links",
    heading: "Affiliate Links and Revenue",
    content: [
      "Outfit Engine surfaces product recommendations that may include affiliate links. When you click an affiliate link and make a purchase, we may receive a commission from the retailer. This does not affect the price you pay.",
      "Affiliate revenue is how Outfit Engine sustains itself. Product recommendations are generated by AI based on style compatibility — affiliation does not influence which products are recommended to you.",
      "We are transparent about this: links in the product catalog and outfit recommendations may be monetized through affiliate programs.",
    ],
  },
  {
    id: "account-termination",
    heading: "Account Termination",
    content: [
      "You may delete your account at any time through account settings or by contacting us. Upon deletion, your personal data and uploaded images will be removed within 30 days.",
      "We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behavior, or misuse the service. We will endeavor to notify you before taking action except in cases of serious or repeated violation.",
      "If Outfit Engine shuts down or the alpha ends, we will provide reasonable notice and an opportunity for you to export your wardrobe data before the service is discontinued.",
      "These terms are governed by the laws of the jurisdiction where Outfit Engine is operated. Any disputes will be handled informally in the first instance — please contact us before pursuing formal action.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="bg-surface text-on-surface min-h-dvh">
      {/* Header */}
      <header className="bg-surface-container-low px-6 md:px-16 lg:px-20 py-16">
        <div className="max-w-[800px] mx-auto">
          <span className="label-text text-on-surface-variant tracking-widest block mb-6">
            LEGAL
          </span>
          <h1 className="font-serif text-display-sm text-on-surface mb-4">
            Terms of Service
          </h1>
          <p className="text-body-lg text-on-surface-variant">
            Last updated {LAST_UPDATED}
          </p>
        </div>
      </header>

      {/* Intro */}
      <section className="px-6 md:px-16 lg:px-20 py-12">
        <div className="max-w-[800px] mx-auto">
          <p className="text-body-lg text-on-surface-variant">
            These terms govern your use of Outfit Engine, an AI-powered personal
            styling platform currently in early alpha. Please read them. They
            are written to be straightforward rather than to obscure your rights.
          </p>
        </div>
      </section>

      {/* Sections */}
      <div className="px-6 md:px-16 lg:px-20 pb-24">
        <div className="max-w-[800px] mx-auto">
          {sections.map((section, i) => (
            <section
              key={section.id}
              className={i % 2 === 0 ? "py-12" : "bg-surface-container-low px-8 py-12 -mx-8"}
            >
              <span className="label-text text-on-surface-variant tracking-widest block mb-4">
                {String(i + 1).padStart(2, "0")}
              </span>
              <h2 className="font-serif text-headline-sm text-on-surface mb-6">
                {section.heading}
              </h2>
              <div className="space-y-4">
                {section.content.map((paragraph, j) => (
                  <p key={j} className="text-body-lg text-on-surface-variant">
                    {paragraph}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-surface-container-low px-6 md:px-16 lg:px-20 py-10">
        <div className="max-w-[800px] mx-auto flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <span className="label-text text-on-surface-variant tracking-widest">
            &copy; {new Date().getFullYear()} OUTFIT ENGINE
          </span>
          <div className="flex gap-6">
            <Link
              href="/privacy"
              className="label-text text-on-surface-variant tracking-widest hover:text-on-surface transition-colors"
            >
              PRIVACY POLICY
            </Link>
            <Link
              href="/"
              className="label-text text-on-surface-variant tracking-widest hover:text-on-surface transition-colors"
            >
              BACK TO APP
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
